### ISSUE TITLE
RPM / Pressure control

### ISSUE THREAD

**Issue by peter-dolkens** [ankohanse/hass-dab-pumps#32]
I'd love to be able to adjust the pressure (SP) and RPM of my pump manually.

Most of the time we'd like to have low pressure and flow rates due to limited water on the property, but for some functions (showers, certain types of washing, etc) we may need higher pressure.

I'd love to be able to create an automation that increases the pressure/RPM and then sets it back to our regular settings once the flow rate drops to 0 for a period of time.

DAB has a shower boost mode, but that is only timer based. I have access to flow rate, presence sensors, and a swathe of other information that could provide greater convenience and greater savings than the time based approach

**Comment by ankohanse** [comment]
![image](https://github.com/ankohanse/hass-dab-pumps/assets/11971893/6fa92c0b-45fb-403c-b10d-07597d9748b1)

Functionality to configure the Setpoint Pressure (SP) was already included into the integration in version 2024.05.1 (7 May 2024).
You can use its unique id to refer to it in automations: 'number.esybox_sp_setpointpressurebar'
(the 'esybox' part can have a different name depending on your pump setup)

In the DAP DConnect/Live Api this is an 'Installer' level setting, so the option will only be available if you have that role in your DAB user account, otherwise (for customer role) it is displayed as read-only sensor. 

If you use an DAB Live account (ESybox mini 3), it seems you will automatically have 'installer' role.
For DConnect accounts (other pumps), you can see and change your role by logging into the DConnect website. Click on your installation, and choose 'Installation Settings' from the menu on the left. Then scroll down on the page to 'Manage Permissions' and if needed delete the user with wrong 'customer' role and add it again with the correct 'installer' role. (deleting the user does not remove the entire account, just removes its rights from this installation).

Note that the customer/installer role is completely independent from the end user/professional role chosen elsewhere. That latter one is used to target newsletters and other communication.

**Comment by peter-dolkens** [comment]
Perfect thanks.I'd set my home assistant as a regular user.Upgrading to installer has reverted the additional configuration.ThanksPeter DolkensOn 9 Jun 2024, at 08:27, Anko Hanse ***@***.***> wrote:﻿
image.png (view on web)
Functionality to configure the Setpoint Pressure (SP) was already included into the integration in version 2024.05.1 (7 May 2024).
You can use its unique id to refer to it in automations: 'number.esybox_sp_setpointpressurebar'
(the 'esybox' part can have a different name depending on your pump setup)
In the DAP DConnect/Live Api this is an 'Installer' level setting, so the option will only be available if you have that role in your DAB user account, otherwise (for customer role) it is displayed as read-only sensor.
If you use an DAB Live account (ESybox mini 3), it seems you will automatically have 'installer' role.
For DConnect accounts (other pumps), you can see and change your role by logging into the DConnect website. Click on your installation, and choose 'Installation Settings' from the menu on the left. Then scroll down on the page to 'Manage Permissions' and if needed delete the user with wrong 'customer' role and add it again with the correct 'installer' role. (deleting the user does not remove the entire account, just removes its rights from this installation).
Note that the customer/installer role is completely independent from the end user/professional role chosen elsewhere. That latter one is used to target newsletters and other communication.
