### ISSUE TITLE
Is DAB Live down?

### ISSUE THREAD

**Issue by Blake-James** [ankohanse/hass-dab-pumps#35]
I suddenly stopped receiving all data into HA from my Easybox mini 3 on 11:54pm on July 29th here in Victoria, Australia.
In trying to fix it today, I've realised that I can't log into DAB Live on my phone at all any more. I've tried multiple password resets, but each time that I try to log in it just hangs on the loading wheel for 1-2 minutes before saying "Wrong email or password".

**Comment by JHAvanGestel** [comment]
I'm also experiencing the same issue with DAB Live.
Did a fresh install on HA but cannot get past login step.
DConnect does seem to work on phone though.

**Comment by ankohanse** [comment]
Sorry for my late response, was away for a couple of days.
If the DAB Live app and/or website are not accessable, then that indicates it is a problem on the DAB backend servers side. In such a case the integration also will not able to refresh its data since it connects in the exact same way as the DAB Live app does. The integration will aslo not be able to do a fresh install, since that requires a login to the backend servers as well.

Did a quick test today on the integration using a DAB Live account that a friendly user of the integration shared with me. All seems to work fine for that account/installation.

@Blake-James , @JHAvanGestel   do you still have the issues you had a few days ago, or has it already been resolved on the DAB backend server side?

**Comment by Blake-James** [comment]
@ankohanse thanks for looking into this. I just tried logging into DAB Live and also tried DConnect on my phone and still no luck with either of them.

**Comment by JHAvanGestel** [comment]
Works for me (fresh install)

**Comment by ankohanse** [comment]
@Blake-James  is your DAB Live account still causing issues to login into the app and the integration?
Have you tried to ask DAB Pumps if something is wrong with your account?

**Comment by Blake-James** [comment]
@ankohanse yeah I'm still having the same issue unfortunately. I submitted support requests to multiple locations online with DAB, including the form at the bottom of this page https://internetofpumps.com/private-users/
and I also tried going through my local supplier, who tried to contact DAB too but haven't been able to get any response.

**Comment by ankohanse** [comment]
@Blake-James  How annoying for you! Only workaround I can think of is to try to create a new DAB Live account using another email account (if you got another one). And then to link your pump to that new account. But I hope that DAB Pumps will react and resolve things for you before you need to revert to such alternative measures.

**Comment by ankohanse** [comment]
Close due to 3 months of inactivity

**Comment by Blake-James** [comment]
I've finally fixed this after months of trying to get support from DAB. Eventually I got through to the distributer Whites International who after a few weeks have said:
"Our IoT and IT Team have been working on it and it seems the account was locked due to too many incorrect login attempts. The account has now been unlocked so you should be able to access."
What a mess for such a simple issue.
