### ISSUE TITLE
Sensors without State Class since HA 2024.10.x

### ISSUE THREAD

**Issue by mattenz** [ankohanse/hass-dab-pumps#44]
**Describe the bug**
Since updating to 2024.10.x of Home Assistant, I'm getting repair notifications for the following sensors:
![image](https://github.com/user-attachments/assets/1e9a11b3-8971-42a2-b3ed-8f8f73c77f0c)

I can confirm that the sensors are still receiving data so I don't think I want to do what the repair suggests and delete them, right?
![image](https://github.com/user-attachments/assets/ed2f19fb-b175-4ffb-bfc8-f311ce9e4312)

**To Reproduce**
I'm not sure if this is just my instance or if others are seeing it as well, but if it is reproducible, just update to 2024.10

**Additional context**
Running version 20244.10.1 of Hass-DAB-Pumps via DConnect

**Comment by ankohanse** [comment]
This was changed because Home Assistant does not allow (gives a warning) the combination of DeviceClass 'Water' and StateClass 'Total Increasing', 'Total' or 'Measurement'.
The chosen solution was to keep the DeviceClass 'Water', but remove the StateClass. As a result, statistics are no longer gathered for fields 'Last_Period_Flow_Counter' and 'Last_Period_Flow_Counter_Gall'. Which is consistent with existing behavior for 'Last_Period_Energy_Counter'.

If you do want to see statistics for these values then 'Actual_Period_Flow_Counter' is a better entitity to use.

You can safely remove the old statistics for 'Last_Period_Flow_Counter', it will not remove the entity itself. Old statistics for 'Actual_Period_Flow_Counter' will still be there.
